<?php

$cars = [
    [
        'id'=> 1,
        'prezzo'=> 21750.00,
        'chilometraggio'=> 32456,
        'marca'=> 'Fiat',
        'modello'=> '500X',
        'cilindrata'=> 1800,
        'cavalli'=> 150,
        'tipo di carburante'=> 'benzina',
        'cambio'=> 'manuale',
        'trazione'=> 'anteriore',
        'anno di immatricolazione'=> 2018,
        'numero di vecchi proprietari'=> 2,
        'condizioni generali'=> 'autovettura in buone condizioni',
        'capacità serbatoio'=> 48,
        'peso'=> 1320,                                
        'lunghezza'=> 427.00,
        'larghezza'=> 180.00,
        'altezza'=> 160.00,
        'pneumatici'=> '215/60 R16 92V',
        'tipo di freni'=> 'semi-metalliche Brembo',
        'sospensioni'=> 'Sospensioni pneumatiche Bilstein',
        'colore'=> 'rosso',
        'numero porte'=> 5,
        'numero posti'=> 5,
        'capacità bagagliaio'=> 350,
        'foto'=> 'https://immagini.alvolante.it/sites/default/files/styles/anteprima_lunghezza_640_jpg/public/serie_auto_galleria/2014/11/fiat_500x_ant_2.png?itok=5p9zPHUR',
    ],
    [
        'id'=> 2,
        'prezzo'=> 31900.00,
        'chilometraggio'=> 46985,
        'marca'=> 'Jeep',
        'modello'=> 'Compass',
        'cilindrata'=> 2000,
        'cavalli'=> 180,
        'tipo di carburante'=> 'diesel',
        'cambio'=> 'automatico',
        'trazione'=> '4x4',
        'anno di immatricolazione'=> 2020,
        'numero di vecchi proprietari'=> 4,
        'condizioni generali'=> 'autovettura in ottime condizioni',
        'capacità serbatoio'=> 60,
        'peso'=> 1720,                                
        'lunghezza'=> 440.00,
        'larghezza'=> 187.00,
        'altezza'=> 163.00,
        'pneumatici'=> '254/98 R15 81V',
        'tipo di freni'=> 'acciaio basso Ferodo',
        'sospensioni'=> 'Sospensioni idropneumatiche Monroe',
        'colore'=> 'bianco',
        'numero porte'=> 5,
        'numero posti'=> 5,
        'capacità bagagliaio'=> 650,
        'foto'=> 'https://immagini.alvolante.it/sites/default/files/styles/anteprima_lunghezza_640_jpg/public/serie_auto_galleria/2017/05/jeep_compass_ant.png?itok=-wBKDN3Y',
    ],
    [
        'id'=> 3,
        'prezzo'=> 79340.00,
        'chilometraggio'=> 10985,
        'marca'=> 'Maserati',
        'modello'=> 'Levante',
        'cilindrata'=> 3000,
        'cavalli'=> 275,
        'tipo di carburante'=> 'benzina',
        'cambio'=> 'automatico',
        'trazione'=> 'posteriore',
        'anno di immatricolazione'=> 2019,
        'numero di vecchi proprietari'=> 1,
        'condizioni generali'=> 'gomme nuove, freni sostituiti, catena sostituita, in ottime condizioni',
        'capacità serbatoio'=> 60,
        'peso'=> 1820,                                
        'lunghezza'=> 500.00,
        'larghezza'=> 198.00,
        'altezza'=> 169.00,
        'pneumatici'=> '225/57 R15 48V',
        'tipo di freni'=> 'ceramiche ATE',
        'sospensioni'=> 'Sospensioni a barre di torsioneGabriel',
        'colore'=> 'nero',
        'numero porte'=> 5,
        'numero posti'=> 5,
        'capacità bagagliaio'=> 798,
        'foto'=> 'https://immagini.alvolante.it/sites/default/files/styles/anteprima_lunghezza_640_jpg/public/serie_auto_galleria/2016/04/maserati_levante_ant.png?itok=LHQRBAaK',
    ],
    [
        'id'=> 4,
        'prezzo'=> 5340.00,
        'chilometraggio'=> 65456,
        'marca'=> 'Suzuki',
        'modello'=> 'Swift',
        'cilindrata'=> 1200,
        'cavalli'=> 75,
        'tipo di carburante'=> 'ibrido',
        'cambio'=> 'manuale',
        'trazione'=> 'anteriore',
        'anno di immatricolazione'=> 2015,
        'numero di vecchi proprietari'=> 3,
        'condizioni generali'=> 'La macchina è ben accessoriata, ha sensori di parcheggio anteriori e posteriori, fendinebbia anteriori e posteriori, stop posteriori led, sedili stoffa e alcantara, comandi al volante, bluetooth, usb, aux, cd, navigatore, doppie chiavi con chiusura centralizzata.
        Revisione delle bombole appena effettuata presso la volkswagen.',
        'capacità serbatoio'=> 45,
        'peso'=> 1420,                                
        'lunghezza'=> 385.00,
        'larghezza'=> 174.00,
        'altezza'=> 148.00,
        'pneumatici'=> '218/49 R15 35V',
        'tipo di freni'=> 'semi-metalliche Brembo',
        'sospensioni'=> 'Sospensioni a molle elicoidali Fox',
        'colore'=> 'giallo',
        'numero porte'=> 3,
        'numero posti'=> 4,
        'capacità bagagliaio'=> 265,
        'foto'=> 'https://immagini.alvolante.it/sites/default/files/styles/anteprima_lunghezza_640_jpg/public/serie_auto_galleria/2017/03/suzuki_swuift_ant.png?itok=32yBAG5-',
    ],
    [
        'id'=> 5,
        'prezzo'=> 15340.00,
        'chilometraggio'=> 40456,
        'marca'=> 'Mini',
        'modello'=> 'Clubman',
        'cilindrata'=> 1700,
        'cavalli'=> 120,
        'tipo di carburante'=> 'benzina',
        'cambio'=> 'automatico',
        'trazione'=> 'integrale',
        'anno di immatricolazione'=> 2018,
        'numero di vecchi proprietari'=> 2,
        'condizioni generali'=> 'Veicolo tagliandato a settembre 2021,con cambio cinghia di distribuzione fatto',
        'capacità serbatoio'=> 50,
        'peso'=> 1620,                                
        'lunghezza'=> 386.00,
        'larghezza'=> 173.00,
        'altezza'=> 142.00,
        'pneumatici'=> '257/65 R15 45V',
        'tipo di freni'=> 'ceramiche ATE',
        'sospensioni'=> 'Sospensioni idrauliche Koni',
        'colore'=> 'verde metallizzato',
        'numero porte'=> 3,
        'numero posti'=> 4,
        'capacità bagagliaio'=> 160,
        'foto'=> 'https://immagini.alvolante.it/sites/default/files/styles/anteprima_lunghezza_640_jpg/public/serie_auto_galleria/2015/10/mini_clubman_ant_2.png?itok=NnBtytMW',
    ],
    [
        'id'=> 6,
        'prezzo'=> 13348.00,
        'chilometraggio'=> 17400,
        'marca'=> 'Opel',
        'modello'=> 'Mokka',
        'cilindrata'=> 1400,
        'cavalli'=> 100,
        'tipo di carburante'=> 'benzina',
        'cambio'=> 'automatico',
        'trazione'=> 'anteriore',
        'anno di immatricolazione'=> 2021,
        'numero di vecchi proprietari'=> 1,
        'condizioni generali'=> 'motore perfetto, tagliandi certificati. cambio automatico da rifare',
        'capacità serbatoio'=> 60,
        'peso'=> 1820,                                
        'lunghezza'=> 415.00,
        'larghezza'=> 179.00,
        'altezza'=> 152.00,
        'pneumatici'=> '257/65 R15 55V',
        'tipo di freni'=> 'organiche Bosch',
        'sospensioni'=> 'Sospensioni ad elastomeri Rancho',
        'colore'=> 'bronzo',
        'numero porte'=> 5,
        'numero posti'=> 5,
        'capacità bagagliaio'=> 350,
        'foto'=> 'https://immagini.alvolante.it/sites/default/files/styles/anteprima_lunghezza_640_jpg/public/serie_auto_galleria/2021/03/opel_mokka_ant.png?itok=o_xH2s2F',
    ],
    [
        'id'=> 7,
        'prezzo'=> 2348.00,
        'chilometraggio'=> 97400,
        'marca'=> 'Seat',
        'modello'=> 'Ibiza',
        'cilindrata'=> 1100,
        'cavalli'=> 70,
        'tipo di carburante'=> 'ibrido',
        'cambio'=> 'manuale',
        'trazione'=> 'anteriore',
        'anno di immatricolazione'=> 2015,
        'numero di vecchi proprietari'=> 3,
        'condizioni generali'=> 'volano frizione leggermente rumoroso, la fiancata destra dell\'auto ha la vernice un pò scolorita, tessuto del cielo scollato nella parte posteriore',
        'capacità serbatoio'=> 55,
        'peso'=> 1520,                                
        'lunghezza'=> 406.00,
        'larghezza'=> 178.00,
        'altezza'=> 144.00,
        'pneumatici'=> '257/55 R15 40V',
        'tipo di freni'=> 'ceramiche ATE',
        'sospensioni'=> 'Sospensioni idrauliche Koni',
        'colore'=> 'blu',
        'numero porte'=> 5,
        'numero posti'=> 5,
        'capacità bagagliaio'=> 262,
        'foto'=> 'https://immagini.alvolante.it/sites/default/files/styles/anteprima_lunghezza_640_jpg/public/serie_auto_galleria/2017/04/seat_ibiza_ant.png?itok=Z1uNeBNX',
    ],
    [
        'id'=> 8,
        'prezzo'=> 53658.00,
        'chilometraggio'=> 65486,
        'marca'=> 'Volvo',
        'modello'=> 'XC90',
        'cilindrata'=> 2000,
        'cavalli'=> 310,
        'tipo di carburante'=> 'benzina',
        'cambio'=> 'automatico',
        'trazione'=> '4x4',
        'anno di immatricolazione'=> 2022,
        'numero di vecchi proprietari'=> 1,
        'condizioni generali'=> 'auto in ottime condizioni',
        'capacità serbatoio'=> 65,
        'peso'=> 1920,                                
        'lunghezza'=> 495.00,
        'larghezza'=> 201.00,
        'altezza'=> 178.00,
        'pneumatici'=> '257/65 R20 70V',
        'tipo di freni'=> 'ceramiche ATE',
        'sospensioni'=> 'Sospensioni idrauliche Koni',
        'colore'=> 'nera',
        'numero porte'=> 5,
        'numero posti'=> 7,
        'capacità bagagliaio'=> 709,
        'foto'=> 'https://immagini.alvolante.it/sites/default/files/styles/anteprima_lunghezza_640_jpg/public/serie_auto_galleria/2014/10/volvo_xc90_ant_0.png?itok=Wz32BhG5',
    ],
    [
        'id'=> 9,
        'prezzo'=> 3658.00,
        'chilometraggio'=> 15785,
        'marca'=> 'Toyota',
        'modello'=> 'Hilux',
        'cilindrata'=> 1700,
        'cavalli'=> 120,
        'tipo di carburante'=> 'benzina',
        'cambio'=> 'manuale',
        'trazione'=> '4x4',
        'anno di immatricolazione'=> 2016,
        'numero di vecchi proprietari'=> 5,
        'condizioni generali'=> 'auto preticamente nuova, dotata di kit di protezione sottoscocca alluminio, varicello e pedane',
        'capacità serbatoio'=> 45,
        'peso'=> 1520,                                
        'lunghezza'=> 533.00,
        'larghezza'=> 186.00,
        'altezza'=> 181.00,
        'pneumatici'=> '257/54 R19 65V',
        'tipo di freni'=> 'semi-metalliche Brembo',
        'sospensioni'=> 'Sospensioni a balestra Ohlins',
        'colore'=> 'marrone',
        'numero porte'=> 5,
        'numero posti'=> 4,
        'capacità bagagliaio'=> 1000,
        'foto'=> 'https://immagini.alvolante.it/sites/default/files/styles/anteprima_lunghezza_640_jpg/public/serie_auto_galleria/2016/06/toyota_hilux_ant.png?itok=L_NsO1iR',
    ],
    [
        'id'=> 10,
        'prezzo'=> 46558.00,
        'chilometraggio'=> 1000,
        'marca'=> 'Chevrolet',
        'modello'=> 'Camaro Coupé',
        'cilindrata'=> 6200,
        'cavalli'=> 453,
        'tipo di carburante'=> 'benzina',
        'cambio'=> 'sequenziale',
        'trazione'=> 'posteriore',
        'anno di immatricolazione'=> 2021,
        'numero di vecchi proprietari'=> 1,
        'condizioni generali'=> 'auto in buone condizioni con sedili riscaldati',
        'capacità serbatoio'=> 60,
        'peso'=> 1521,                                
        'lunghezza'=> 478.00,
        'larghezza'=> 188.00,
        'altezza'=> 135.00,
        'pneumatici'=> '257/36 R19 53V',
        'tipo di freni'=> 'ceramiche Brembo',
        'sospensioni'=> 'Sospensioni idrauliche Ohlins',
        'colore'=> 'giallo',
        'numero porte'=> 3,
        'numero posti'=> 4,
        'capacità bagagliaio'=> 257,
        'foto'=> 'https://immagini.alvolante.it/sites/default/files/styles/anteprima_lunghezza_640_jpg/public/serie_auto_galleria/2016/08/chevrolet_camaro_ant.png?itok=B2F1seBt',
    ],
]

?>